# 白名单模式

proxy-providers:
  # 获取机场订阅链接内的所有节点
  🛫 我的机场:
    type: http
    # 机场订阅链接，使用 Clash 链接
    url: 'https://sanfen003.xyz/api/v1/client/subscribe?token=075ea7d2cdac67fc271b165426ba3dab&flag=clash'
    path: ./proxies/airport.yaml
    interval: 86400
    health-check:
      enable: true
      interval: 600
      # 未选择到当前策略组时，不会进行测试
      # lazy: true
      url: 'https://www.gstatic.com/generate_204'

proxy-groups:
  - name: 🚀 节点选择
    # 手动选择节点（下同）
    type: select
    proxies:
      # 根据 proxy-groups 中（下方）国家或地区的节点名称进行增删改，一一对应
      - 🇭🇰 香港节点
      - 🇹🇼 台湾节点
      - 🇰🇷 韩国节点
      - 🇯🇵 日本节点
      - 🇸🇬 新加坡节点

  # Speedtest 测速网站
  - name: 📈 网络测速
    type: select
    proxies:
      # 测试本地网络速度（运营商网络速度）
      - 🎯 全球直连
      # 测试机场速度（翻墙后网络速度）
      - 🚀 节点选择

  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连

  - name: 🇨🇳 国内域名
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择

  - name: 🪜 国外域名
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连

  - name: 🎮 国区游戏
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择

  - name: Ⓜ️ Microsoft 中国
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择

  - name: 🗽 Google 中国
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择

  - name: 🍎 Apple 中国
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择

  - name: 🀄 国内 IP 地址
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择

  - name: ✈️ Telegram IP 地址
    type: select
    proxies:
      - 🚀 节点选择

  - name: 🏠 私有网络
    type: select
    proxies:
      - 🎯 全球直连

  - name: ⛔️ 广告域名
    type: select
    proxies:
      - 🛑 全球拦截

  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT

  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT

  # 国家或地区节点
  - name: 🇭🇰 香港节点
    # 自动选择，即按照 url 测试结果使用延迟最低的节点（下同）
    type: url-test
    # 容差大于 100ms 就会切换到延迟低的那个节点
    tolerance: 100
    use:
      # 使用 proxy-providers 中的节点名称（下同）
      - 🛫 我的机场
    # 筛选出“香港”节点，支持正则表达式（下同）
    filter: "香港"

  - name: 🇹🇼 台湾节点
    type: url-test
    tolerance: 100
    use:
      - 🛫 我的机场
    filter: "台湾"

  - name: 🇰🇷 韩国节点
    type: url-test
    tolerance: 100
    use:
      - 🛫 我的机场
    filter: "韩国"

  - name: 🇯🇵 日本节点
    type: url-test
    tolerance: 100
    use:
      - 🛫 我的机场
    filter: "日本"

  - name: 🇸🇬 新加坡节点
    type: url-test
    tolerance: 100
    use:
      - 🛫 我的机场
    filter: "新加坡"

rule-providers:
  # 规则集名称（下同）
  speedtest:
    type: http
    # 行为：[domain]-仅包含域名 [ipcidr]-仅包含 IP 地址 [classical]-全部包含（下同）
    behavior: domain
    url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Speedtest/Speedtest.yaml'
    path: ./ruleset/speedtest.yaml
    interval: 86400

  microsoft:
    type: http
    behavior: domain
    url: 'https://rules.kr328.app/microsoft@cn.yaml'
    path: ./ruleset/microsoft.yaml
    interval: 86400

  games:
    type: http
    behavior: domain
    url: 'https://rules.kr328.app/category-games@cn.yaml'
    path: ./ruleset/games.yaml
    interval: 86400

  reject:
    type: http
    behavior: domain
    url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt'
    path: ./ruleset/reject.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt'
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt'
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt'
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt'
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt'
    path: ./ruleset/private.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt'
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt'
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt'
    path: ./ruleset/lancidr.yaml
    interval: 86400

rules:
  # 自定义规则优先放前面
  - RULE-SET,reject,⛔️ 广告域名
  - RULE-SET,private,🏠 私有网络
  - RULE-SET,speedtest,📈 网络测速
  - RULE-SET,microsoft,Ⓜ️ Microsoft 中国
  - RULE-SET,apple,🍎 Apple 中国
  - RULE-SET,google,🗽 Google 中国
  - RULE-SET,games,🎮 国区游戏
  - RULE-SET,proxy,🪜 国外域名
  - RULE-SET,direct,🇨🇳 国内域名
  - RULE-SET,lancidr,🏠 私有网络
  - RULE-SET,cncidr,🀄 国内 IP 地址
  - RULE-SET,telegramcidr,✈️ Telegram IP 地址
  - MATCH,🐟 漏网之鱼
